### ISSUE TITLE
QMutex: destroying locked mutex

### ISSUE THREAD

**Issue by despzcm** [CoppeliaRobotics/simPovRay#2]
I am working on a coppeliasim project and when I try to run the .ttt file, the sim crash and get the error as follow:

```
Error: signal 11:

/home/a/coppeliasim/libcoppeliaSim.so(_segHandler(int)+0x40) [0x7feff01c2940]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7feff2ded520]
/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so(+0xc25f2d) [0x7fefdab4af2d]
QMutex: destroying locked mutex
```
How can I solve this problem

**Comment by despzcm** [comment]
The version of my coppeliasim is v4.7 and I run on ubuntu 22.04

**Comment by WAYKEN-TSE** [comment]
hi，I face the same problem when working on a coppeliasim project, could u tell me how to fix it?hope for your replyl,thanks
